# This CI jobs based on open-source workflows project:
#  https://github.com/bitPogo/workflows/blob/main/.github/workflows/shared-build-macos.yml

name: Build on macos

on:
  workflow_call:

jobs:
  build-on-macOS:
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Cache Konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ github.sha }}
            ${{ runner.os }}-konan-

      - name: Cache BuildCache
        uses: actions/cache@v4
        with:
          path: '**/.gradle/build-cache/**'
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: Build
        run: ./gradlew build -x check --stacktrace