name: Mobile app base workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  coverage:
    uses: ./.github/workflows/ci-sonar-linux.yml

  test_android:
      uses: ./.github/workflows/ci-build-android.yml