name: Mobile app base workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-on-linux:
    uses: ./.github/workflows/ci-build-on-linux.yml

  build-on-macos:
    uses: ./.github/workflows/ci-build-on-macos.yml

  test_android:
      uses: ./.github/workflows/ci-test-android.yml

#  coverage:
#    uses: ./.github/workflows/ci-sonar-linux.yml