name: Mobile app base workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-on-linux:
    uses: ./.github/workflows/ci-build-on-linux.yml

  build-on-macos:
    uses: ./.github/workflows/ci-build-on-macos.yml

  test-android:
    needs: build-on-linux
    uses: ./.github/workflows/ci-test-android.yml
    with:
      coverage: true

  coding-convention:
    needs: [ build-on-macos, test-android ]
    uses: ./.github/workflows/ci-coding-convention.yml

  coverage:
    needs: [ test-android ]
    uses: ./.github/workflows/ci-coverage.yml